service: time-tracker-api

frameworkVersion: "~3.34.0"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  role: arn:aws:iam::556479867163:role/role-for-time-tracker
  stage: prod
  deploymentBucket:
    name: time-tracker-code-bucket
  memorySize: 256
  timeout: 10
  environment:
    NODE_ENV: production

functions:
  api:
    handler: dist/handler.handler
    events:
      - http:
          path: /users
          method: POST
          authorizer:
            name: authLambda
            type: token
      - httpApi:
          path: /time-entries
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY   # catch-all para outras rotas

plugins:
  - serverless-offline
